name: Deploy to MvM infra repo

on:
  push:
    branches: [ main ]

jobs:
  pr_to_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infrastructure
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          repository: "moedersvoormoeders/infrastructure"
          path: "infrastructure"

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{secrets.BOT_TOKEN}}
        run: |
          cd infrastructure
          git config --local user.email "expino-bot@mect.io"
          git config --local user.name "mect-bot"
          git checkout -b deploy-expino-$GITHUB_SHA
          mkdir imagetags || true
          echo "$GITHUB_SHA" >imagetags/expino-sha
          git add .
          git commit -m "Deploy Expino $GITHUB_SHA"
          git push --set-upstream origin deploy-expino-$GITHUB_SHA
          gh pr create --title "Deploy Expino $GITHUB_SHA" --body "Deploy $GITHUB_SHA of Expino" --repo github.com/thehivebot/infrastructure